project:
  name: "test"
  version: "1.0.0"
  team: "shikigami"
  description: "Mi proyecto de ejemplo"
  organization: "fastdeploy"

template:
  repository_url: "https://github.com/jairoprogramador/mydeploytest.git"
  ref: "main"

technology:
  stack: "springboot"
  infrastructure: "azure"

runtime:
  core_version: "1.0.3"
  image:
    #source: "fastdeploy/runner-java"
    tag: "1.2.0"
  volumes:
    - host: "projectPath"
      container: "/home/fastdeploy/app"
    - host: "statePath"
      container: "/home/fastdeploy/.fastdeploy"
    - host: "/home/jairo/.m2/"
      container: "/home/fastdeploy/.m2"

state:
  backend: "local"
  url: ""
